config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @user = User.first
    @book = @user.books.build
  end

  def edit
  end

  def create
    @user = User.first
    @book = @user.books.build(book_params)

    respond_to do |format|
      if @book.save
        BookMailer.with(user: @user, book_title: @book.title).create_book_email.deliver_now
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="border rounded my-5 p-5">
  <div class="row">
    <div class="col-1">
      <p class="text-muted">
        Title
      </p>
      <p class="text-muted">
        User
      </p>
    </div>

    <div class="col">
      <p class="text-success">
        <%= book.title %>
      </p>
      <p class="text-success">
        <%= book.user.name %>
      </p>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<div class="card shadow my-5 p-5">
  <%= simple_form_for(@book) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%#= f.association :user %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-sm btn-outline-success my-3' %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1 class="text-success text-center">
  Editing book
</h1>

<%= render "form", book: @book %>

<br>

<div class="btn-group">
  <%= link_to "Show this book", @book, class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to "Back to books", books_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/books/index.html.erb
<p style="color: green">
  <%= notice %>
</p>

<h1 class="text-muted text-center">
  Books
</h1>

<% @books.each do |book| %>
  <div class="card shadow my-5 p-5">
    <%= render book %>
    <p><%= link_to "Show this book", book, class: 'btn btn-sm btn-outline-primary mt-3' %></p>
  </div>
<% end %>

<%= link_to "New book", new_book_path, class: 'btn btn-sm btn-outline-primary' %>

app/views/books/new.html.erb
<h1 class="text-muted text-center">
  New book
</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/books/show.html.erb
<p style="color: green">
  <%= notice %>
</p>

<%= render @book %>

<div class="btn-group">
  <%= link_to "Edit this book", edit_book_path(@book), class: 'btn btn-sm btn-outline-warning' %>
  <%= link_to "Back to books", books_path, class: 'btn btn-sm btn-outline-secondary' %>
  <%= button_to "Destroy this book", @book, method: :delete, class: 'btn btn-sm btn-outline-danger' %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand mx-5" href="/">Emails</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= users_path %>">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= books_path %>">Books</a>
        </li>
        <li class="nav-item ms-5">
          <a class="nav-link" href="<%= new_user_path %>">Create User</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_book_path %>">Create Book</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header class="container">
      <%= render 'layouts/nav' %>
    </header>

    <main class="container my-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<div class="card shadow my-5 p-5">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :email %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-sm btn-outline-success' %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="border rounded my-5 p-5">
  <div class="row">
    <div class="col-1">
      <p class="text-muted">
        Name
      </p>
      <p class="text-muted">
        Email
      </p>
    </div>

    <div class="col">
      <p class="text-success">
        <%= user.name %>
      </p>
      <p class="text-success">
        <%= user.email.present? ? user.email : 'NO EMAIL' %>
      </p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center text-muted">
  Editing user
</h1>

<%= render "form", user: @user %>

<br>

<div class="btn-group">
  <%= link_to "Show this user", @user, class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to "Back to users", users_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/users/index.html.erb
<p style="color: green">
  <%= notice %>
</p>

<h1 class="text-muted text-center">
  Users
</h1>

<% @users.each do |user| %>
  <div class="card shadow my-5 p-5">
    <%= render user %>
    <p><%= link_to "Show this user", user, class: 'btn btn-sm btn-outline-primary mt-3' %></p>
  </div>
<% end %>

<%= link_to "New user", new_user_path, class: 'btn btn-sm btn-outline-primary' %>

app/views/users/new.html.erb
<h1 class="text-muted text-center">
  New user
</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/users/show.html.erb
<p style="color: green">
  <%= notice %>
</p>

<%= render @user %>

<div class="btn-group">
  <%= link_to "Edit this user", edit_user_path(@user), class: 'btn btn-sm btn-outline-warning' %>
  <%= link_to "Back to users", users_path, class: 'btn btn-sm btn-outline-secondary' %>
  <%= button_to "Destroy this user", @user, method: :delete, class: 'btn btn-sm btn-outline-danger' %>
</div>